development:
  #adapter: async
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: marketing_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: marketing_production
